version: "3.8"
services:
  postgres_db:
    image: postgres:latest
    container_name: postgres_container
    environment:
      POSTGRES_DB: 'cyclehub'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: '9207400638'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    volumes:
      - .:/app
    container_name: cyclehub_container
    ports:
      - 8090:8000
    image: app:cyclehub

    command: bash -c "apt-get update && apt-get install -y postgresql-client && gunicorn --bind 0.0.0.0:8000 cyclehub.wsgi:application && python manage.py collectstatic && python manage.py makemigrations "

    depends_on:
      - postgres_db
  
volumes:
  postgres_data: